### ISSUE TITLE
Closing issues

### ISSUE THREAD

**Issue by aude** [Hedgehogs4Me/tile-collector-simulator#3]
I think one of the biggest incentives to use GitHub issues to manage the project is that it feels really rewarding to completely solve an issue and then closing it.

As such I suggest that we create small, concrete and tangible issues, that are optimized for closing. If a new idea arises while in the middle of an issue, create a new issue.

If you agree, you can close this issue.

**Comment by Hedgehogs4Me** [comment]
Good idea, but I think this should be for code only, not conceptual stuff like figuring out how stuff works. It'll also let us comment specifically about those topics in an organized fashion without confusion.

**Comment by aude** [comment]
Okay. The _enhancement_ issue label could be used for discussion topics. Then we can disregard them from open issues.
